### ISSUE TITLE
getScrollResponder does not exits

### ISSUE THREAD

**Issue by femiveys** [deanmcpherson/react-native-sortable-listview#69]
When running a snapshot test wit jest on a component using the `SortableListView`, I get following error:

```
node_modules/react-native-sortable-listview/index.js:186
_this3.scrollResponder=_this3.refs.list.getScrollResponder();
                                        ^
TypeError: _this3.refs.list.getScrollResponder is not a function
    at null._onTimeout (node_modules/react-native-sortable-listview/index.js:186:41)
    at Timer.listOnTimeout (timers.js:92:15)
npm ERR! Test failed.  See above for more details.

```

When I look into the `refs.list`, indeed the getScrollResponder() doesn't exits.

I run react native 0.42.3
And version 0.2.2 of this module

Is there something special I should do with snapshot tests? I followed the example.

**Comment by pgonzalez-santiago** [comment]
Same here. any news?

**Comment by femiveys** [comment]
No, I have not been able to solve this
